#!/usr/bin/env python

import sys
from os.path import expanduser

# installed:
from configobj import ConfigObj

import air.air

config = ConfigObj(expanduser('~/.dev.cfg'))
air.air.Dispatcher(config).go()
sys.exit(0)
