#!/usr/bin/env python

import sys
from os.path import expanduser

# installed:
from configobj import ConfigObj
from path import path

from rair import air

# read the configuration file from $HOME
config = ConfigObj(expanduser('~/.air.cfg'))
# a file in the current directory will override $HOME settings
config.merge(ConfigObj('./.air.cfg'))

air.Dispatcher(config).go()
sys.exit(0)
